services:
    app:
        build: ./src
        ports:
            - 8081:8081
    prometheus:
        build: ./prometheus
        ports:
            - '9090:9090'
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
    grafana:
        image: grafana/grafana
        ports:
            - '3000:3000'
        depends_on:
            - prometheus
    db:
        image: postgres
        shm_size: 128mb
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
